---
# NOTE: Ensure important packages we always want to have are present
# and deploy basic grml-config for user root

- name: Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config
- name: Disable ssh root login with password
  lineinfile: dest=/etc/ssh/sshd_config regexp='^PermitRootLogin' state=absent
  when: sshd_config.stat.exists
  notify: ssh restart
- name: Deploy /etc/apt/trusted.gpg.d/extended-lts-archive-key.gpg
  copy: src=files/apt/extended-lts-archive-key.gpg dest=/etc/apt/trusted.gpg.d/extended-lts-archive-key.gpg owner=root group=root mode=0644
  when:
    - base_enable_elts is defined
    - base_enable_elts == true
    - ansible_distribution_release == "wheezy" or ansible_distribution_release == "jessie" or ansible_distribution_release == "stretch" or ansible_distribution_release == "buster"
- name: Provide /etc/apt/sources.list
  template: src=templates/apt/sources.list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644
  notify: apt-get update
  when: ansible_distribution == 'Debian'
- meta: flush_handlers

- name: Ensure base Debian package selection is installed
  apt:
    name:
      - acl
      - apt-dater-host
      - aptitude
      - bsd-mailx
      - ca-certificates
      - curl
      - dbus
      - etckeeper
      - ethtool
      - git
      - htop
      - iotop
      - jq
      - ldnsutils
      - lsof
      - man-db
      - moreutils
      - needrestart
      - netcat-openbsd
      - parted
      - psmisc
      - rsync
      - screen
      - socat
      - tmux
      - unzip
      - vim
      - wget
      - zsh
      - zstd
    state: present

- name: Install apt-transport-https (for Debian/stretch)
  apt:
    name:
      - apt-transport-https
    state: present
  when: ansible_distribution_release == 'stretch'

- name: Install ntp client / daemon
  apt:
    name:
      - "{{ base_ntp_package }}"
    state: present
  when:
    - base_ntp_package is defined
    - base_ntp_package | length > 0

- name: Deploy ntp client configuration (chrony.conf only)
  template:
    src: "chrony/chrony.{{ ansible_distribution_release }}.conf.j2"
    dest: /etc/chrony/chrony.conf
    mode: 0664
    owner: root
    group: root
  when:
    base_ntp_package == "chrony"
  notify: ntp daemon restart

- name: Make sure ntp service is started + enabled
  service:
    name: "{{ base_ntp_package }}"
    state: started
    enabled: true
  when: base_ntp_enable | bool

- name: Ensure extended base Debian package selection is installed (for VMs)
  apt:
    name:
      - qemu-guest-agent
    state: present
  when:
    ansible_system_vendor == "QEMU"
- name: Ensure extended base Debian package selection is installed (for non-VMs)
  apt:
    name:
      - smartmontools
    state: present
  when:
    ansible_system_vendor != "QEMU"
- name: Set vim as default editor (update-alternative)
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  when: not ansible_check_mode
- name: Provide custom needrestart configuration
  template: src=needrestart/synpro.conf.j2 dest=/etc/needrestart/conf.d/synpro.conf owner=root group=root mode=0644
- name: Check for systemd-sysv
  shell: 'dpkg -l systemd-sysv | grep -e "^ii" -q'
  register: systemd_sysv_installed
  ignore_errors: true
  changed_when: false
  check_mode: false
- name: Install libpam-systemd on Debian/jessie and later systems (with systemd-sysv)
  apt:
    name:
      - libpam-systemd
    state: present
  when:
    systemd_sysv_installed.rc == 0
- name: Create ansible facts.d directory
  file: path=/etc/ansible/facts.d state=directory owner=root group=root mode=0755
- name: Deploy custom ansible facts
  copy: src=ansible_facts.d/services.fact dest=/etc/ansible/facts.d/services.fact owner=root group=root mode=0755

# Two-space indents feel comfortable to me, but do whatever you like.
# vim:ff=unix ts=2 sw=2 ai expandtab
#
