---
# NOTE: Ensure important packages we always want to have are present
# and deploy basic grml-config for user root

- include_tasks: apt-update.yml
- name: Ensure base Debian package selection is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-dater-host
    - apt-transport-https
    - aptitude
    - curl
    - dbus
    - etckeeper
    - ethtool
    - git
    - iotop
    - man-db
    - ldnsutils
    - needrestart
    # Do not install, because proxmox conflicts with this package
    # - netcat-openbsd
    - ntp
    - parted
    - screen
    - socat
    - tmux
    - vim
    - zsh
- name: Ensure extended base Debian package selection is installed (for non-VMs)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - smartmontools
  when:
    ansible_system_vendor != "QEMU"
- name: Set vim as default editor (update-alternative)
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
- name: Provide custom needrestart configuration to disable interactive mode
  copy: src=files/needrestart/synpro.conf dest=/etc/needrestart/conf.d/synpro.conf owner=root group=root mode=0644
- name: Check for systemd-sysv
  shell: 'dpkg -l systemd-sysv | grep -e "^ii" -q'
  register: systemd_sysv_installed
  ignore_errors: true
  changed_when: false
  check_mode: false
- name: Install libpam-systemd on Debian/jessie and later systems
  apt: name=libpam-systemd state=present
  when: systemd_sysv_installed.rc == 0
- include_tasks: grml-config.yml username=root
- name: Create ansible facts.d directory
  file: path=/etc/ansible/facts.d state=directory owner=root group=root mode=0755
- name: Deploy custom ansible facts
  copy: src=ansible_facts.d/services.fact dest=/etc/ansible/facts.d/services.fact owner=root group=root mode=0755

# Two-space indents feel comfortable to me, but do whatever you like.
# vim:ff=unix ts=2 sw=2 ai expandtab
#
