---
# handlers file for ansible-role-base

- name: apt-get update
  apt: update_cache=yes

- name: ssh restart
  service: name=ssh state=restarted

- name: ntp daemon restart
  service:
    name: "{{ base_ntp_package }}"
    state: restarted
  when: base_ntp_enable | bool
