---
# handlers file for ansible-role-base

- name: apt-get update
  apt: update_cache=yes

- name: ssh restart
  service: name=ssh state=restarted

- name: chrony restart
  service: name=chrony state=restarted
