---
- name: Converge
  hosts: all
  become: true
  vars:
    base_ntp_enable: false
    base_ntp_package: 'chrony'
    base_ntp_server: 'time.example.com prefer iburst'

  roles:
    - role: jkirk.base
