---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: debian10
    image: docker.io/debian:buster-slim
    dockerfile: Dockerfile_debian_buster.j2
    privileged: true
    pre_build_image: false
    override_command: false
    tmpfs:
      - /run
      - /tmp
  - name: debian11
    image: docker.io/debian:bullseye-slim
    dockerfile: Dockerfile_debian_bullseye.j2
    privileged: true
    pre_build_image: false
    override_command: false
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
verifier:
  name: ansible
