---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-base"
      include_role:
        name: "ansible-role-base"
      vars:
        base_ntp_package: 'chrony'
        base_ntp_server: 'time.example.com prefer iburst'
        base_ntp_allow:
          - "127/8"
          - "192.168.100.0/24"
        base_ntp_ntpsigndsocket: "/var/lib/samba/ntp_signd"
